---
kind: pipeline
type: docker
name: default

clone:
  disable: true

steps:
  - name: clone
    image: docker.io/bdebyl/alpine-git
    commands:
      - git clone https://github.com/debyltech/go-snipcart-webhook.git .
      - git checkout $DRONE_COMMIT
      - echo -n "0.1.$DRONE_BUILD_NUMBER" > .tags
      - echo -n "latest" >> .tags

  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: debyltech/go-snipcart-webhook
    when:
      event:
        exclude:
          - cron
      branch:
        - master

trigger:
  branch:
  - master
  event:
  - push
---
kind: signature
hmac: 487e584b167ce8387fbdbfeb99bb05ccb4ee80eb12270c5d209625665498c373

...
