---
kind: pipeline
type: docker
name: default

clone:
  disable: true

steps:
  - name: clone
    image: docker.io/bdebyl/alpine-git
    commands:
      - git clone https://github.com/debyltech/go-snipcart-webhook.git .
      - git checkout $DRONE_COMMIT
      - echo -n "0.1.$DRONE_BUILD_NUMBER" > .tags

  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: debyltech/go-snipcart-webhook
    when:
      event:
        exclude:
          - cron
      branch:
        - master

trigger:
  branch:
  - master
---
kind: signature
hmac: 7c441a70c80f0e743c67302bbcfd4799605db5913e499cd815c206ace5406b90

...
